# Generated by Django 6.0.6 on 2026-06-17 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='month_year',
            field=models.CharField(blank=True, default='', max_length=7),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('monthly', 'شهري'), ('per_session', 'بالحصة')], default='per_session', max_length=15),
        ),
    ]
