# Generated by Django 6.0.6 on 2026-06-17 04:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='payment_type',
            field=models.CharField(choices=[('monthly', 'شهري'), ('per_session', 'بالحصة')], default='per_session', max_length=15),
        ),
        migrations.CreateModel(
            name='MemorizationProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('juz_from', models.PositiveSmallIntegerField()),
                ('juz_to', models.PositiveSmallIntegerField()),
                ('notes', models.TextField(blank=True, default='')),
                ('tutor_notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='offers.session')),
            ],
        ),
    ]
