# Generated by Django 6.0.6 on 2026-06-20 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0004_memorizationprogress_cefr_from_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memorizationprogress',
            name='progress_type',
            field=models.CharField(choices=[('quran', 'القرآن الكريم'), ('kindergarten', 'حضانة'), ('languages', 'لغات')], default='quran', max_length=15),
        ),
    ]
