# Generated by Django 6.0.6 on 2026-06-17 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0003_request_payment_type_memorizationprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='memorizationprogress',
            name='cefr_from',
            field=models.CharField(blank=True, default='', max_length=3),
        ),
        migrations.AddField(
            model_name='memorizationprogress',
            name='cefr_to',
            field=models.CharField(blank=True, default='', max_length=3),
        ),
        migrations.AddField(
            model_name='memorizationprogress',
            name='progress_type',
            field=models.CharField(choices=[('quran', 'القرآن الكريم'), ('kindergarten', 'حضانة'), ('language', 'لغات')], default='quran', max_length=15),
        ),
        migrations.AddField(
            model_name='memorizationprogress',
            name='unit_from',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='memorizationprogress',
            name='unit_to',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='memorizationprogress',
            name='juz_from',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='memorizationprogress',
            name='juz_to',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
