# Generated by Django 6.0.6 on 2026-08-03 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0006_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='is_ai_proposed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='session',
            name='is_trial',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='session',
            name='status',
            field=models.CharField(choices=[('awaiting_payment', 'بانتظار الدفع'), ('scheduled', 'Scheduled'), ('done', 'Done')], default='scheduled', max_length=20),
        ),
    ]
