# Generated by Django 6.0.6 on 2026-06-17 03:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('offers', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(default='paypal', max_length=50)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('paypal_order_id', models.CharField(blank=True, default='', max_length=255)),
                ('paypal_capture_id', models.CharField(blank=True, default='', max_length=255)),
                ('webhook_verified', models.BooleanField(default=False)),
                ('payout_batch_id', models.CharField(blank=True, default='', max_length=255)),
                ('tutor_paid', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='offers.session')),
            ],
        ),
    ]
