# Generated by Django 6.0.6 on 2026-06-20 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0004_file_current_cefr_file_current_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='education_level',
            field=models.CharField(choices=[('quran', 'القرآن الكريم'), ('university', 'جامعي'), ('high_school', 'ثانوي'), ('middle_school', 'إعدادي'), ('primary', 'ابتدائي'), ('kindergarten', 'حضانة'), ('languages', 'لغات')], default='university', max_length=15),
        ),
    ]
