# Generated by Django 6.0.6 on 2026-06-23 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0005_alter_file_education_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='end_juz',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='session_duration',
            field=models.PositiveSmallIntegerField(blank=True, default=45, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='sessions_per_week',
            field=models.PositiveSmallIntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
