# Generated by Django 6.0.6 on 2026-06-17 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_last_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='languages',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='student_levels',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='teaching_level',
            field=models.CharField(blank=True, choices=[('quran', 'القرآن الكريم'), ('university', 'جامعي'), ('high_school', 'ثانوي'), ('middle_school', 'إعدادي'), ('primary', 'ابتدائي'), ('kindergarten', 'حضانة'), ('language', 'لغات')], max_length=15, null=True),
        ),
    ]
