# Generated by Django 6.0.6 on 2026-06-20 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_contactrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='teaching_level',
            field=models.CharField(blank=True, choices=[('quran', 'القرآن الكريم'), ('university', 'جامعي'), ('high_school', 'ثانوي'), ('middle_school', 'إعدادي'), ('primary', 'ابتدائي'), ('kindergarten', 'حضانة'), ('languages', 'لغات')], max_length=15, null=True),
        ),
    ]
