# Generated by Django 6.0.6 on 2026-06-17 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='current_juz',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='quran_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='file',
            name='start_juz',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='weekly_availability',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='difficulty',
            field=models.CharField(blank=True, choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='estimated_hours',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='file_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='file',
            name='subject_type',
            field=models.CharField(choices=[('math', 'Math'), ('english', 'English'), ('science', 'Science'), ('quran', 'القرآن الكريم'), ('other', 'Other')], max_length=10),
        ),
    ]
