# Generated by Django 6.0.6 on 2026-06-17 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_file_current_juz_file_quran_notes_file_start_juz_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='current_cefr',
            field=models.CharField(blank=True, default='', max_length=3),
        ),
        migrations.AddField(
            model_name='file',
            name='current_unit',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='education_level',
            field=models.CharField(choices=[('quran', 'القرآن الكريم'), ('university', 'جامعي'), ('high_school', 'ثانوي'), ('middle_school', 'إعدادي'), ('primary', 'ابتدائي'), ('kindergarten', 'حضانة'), ('language', 'لغات')], default='university', max_length=15),
        ),
        migrations.AddField(
            model_name='file',
            name='language',
            field=models.CharField(blank=True, choices=[('english', 'الإنجليزية'), ('french', 'الفرنسية'), ('german', 'الألمانية'), ('spanish', 'الإسبانية'), ('italian', 'الإيطالية'), ('turkish', 'التركية'), ('chinese', 'الصينية'), ('russian', 'الروسية')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='start_cefr',
            field=models.CharField(blank=True, default='', max_length=3),
        ),
        migrations.AddField(
            model_name='file',
            name='start_unit',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
