# Generated by Django 6.0.6 on 2026-08-03 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0006_file_end_juz_file_session_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='language',
            field=models.CharField(blank=True, choices=[('en', 'الإنجليزية'), ('fr', 'الفرنسية'), ('de', 'الألمانية'), ('es', 'الإسبانية'), ('it', 'الإيطالية'), ('tr', 'التركية'), ('zh', 'الصينية'), ('ru', 'الروسية')], max_length=10, null=True),
        ),
    ]
